#!/bin/fish

  set -g res (xrandr | grep '*' | cut -dx -f1)

  set font "Dina:size=11"
  set icons "FontAwesome:size=11"
  set bg "#eeeeeeee"
  set fg "#065F72"

  set py 25
  set pw (math 500-275)
  set px (math $res-25)

function cpu
  set percent (grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage "%"}' | cut -d. -f1)
  echo -n $percent%
end
function ram
  set ram ""
end

if test -z (pgrep -f 'lemonbar -g 400x35')

  echo "%{B$bg}%{l}%{B$bg}%   $info   %{B#00ffffff}" | lemonbar -g 400x35+$px+$py -p -b -f $font -B '#00ffffff' -F $fg | sh

else
    pkill -f 'lemonbar -g 400x35'
    pkill -f 'n30f -d -x2'
    pkill -f 'mpc idleloop'
end
